### ISSUE TITLE
Add enviromnent variable to spec for minecraft container

### ISSUE THREAD

**Issue by guni1192** [guni1192/minecraft-operator#30]
Example:

```yaml
env:
  - key: "RULA"
    value: true
  - key: "WHITE_LIST"
    value: true
```
